"""Beancount text rendering. Pure string formatting, no I/O.

Kept separate from `sync.py` so the exact byte output is unit-testable
without touching the filesystem, and separate from `normalize.py` so a
formatting tweak never risks the SimpleFIN->domain-model transform.
"""

from __future__ import annotations

import json

from bookkeeper.ingest.normalize import (
    AssetAccountOpen,
    NormalizedBalance,
    NormalizedTransaction,
    OpeningBalance,
)

_ACCOUNTS_SIMPLEFIN_HEADER = """\
; Generated by `bookkeeper sync` (bookkeeper.ingest / bookkeeper.simplefin):
; `open` directives for each SimpleFIN-backed Assets:SimpleFIN:<Name> account.
; worker-1 owns this file -- do not hand-edit or open these accounts in
; accounts.beancount, which stays hand-curated for expense/envelope accounts
; only. Rewritten wholesale on every sync from the accounts SimpleFIN
; currently reports; the open date is a fixed sentinel (not derived from any
; account's data) so this file is byte-identical across reruns with no new
; accounts.
"""

_BALANCES_HEADER = """\
; Generated by `bookkeeper sync` (bookkeeper.ingest): SimpleFIN
; `balance`/`balance-date` per account, rendered as beancount `balance`
; assertions. Rewritten wholesale on every sync from the accounts SimpleFIN
; currently reports -- NOT merged with the previous file's contents. If an
; account is closed or its connection is revoked, its assertion disappears
; here too, rather than failing bean-check forever against an account that
; no longer exists (a stale merged-in assertion is a trap, not history --
; see PLAN.md 5.2 item 3, this is the cash-truth guard, not an audit log).
"""


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def render_transaction(txn: NormalizedTransaction) -> str:
    """Render one transaction. `simplefin-id` + `simplefin-account` are the
    dedup key (`ingest/dedup.py`): SimpleFIN ids are unique *per account*,
    not globally -- confirmed live, the real demo server reuses the same id
    across different accounts -- so both fields together, in this fixed
    adjacent order, are what makes re-running sync a no-op instead of
    silently dropping a distinct account's transaction as a false-positive
    duplicate.

    `mcc` / `payee` / `memo` / `extra` are not part of the documented
    protocol but are recorded when the server sends them (observed live on
    the demo server) -- omitted entirely when absent, so a real bank feed
    that sends none of them renders identically to before these existed.
    `extra` is JSON-encoded with sorted keys so the line is deterministic
    across runs (idempotency depends on it).
    """
    narration = _escape(txn.description)
    lines = [
        f'{txn.posted_date.isoformat()} * "{narration}"',
        f'  simplefin-id: "{txn.simplefin_id}"',
        f'  simplefin-account: "{txn.asset_account}"',
    ]
    if txn.mcc is not None:
        lines.append(f'  simplefin-mcc: "{_escape(txn.mcc)}"')
    if txn.payee is not None:
        lines.append(f'  simplefin-payee: "{_escape(txn.payee)}"')
    if txn.memo is not None:
        lines.append(f'  simplefin-memo: "{_escape(txn.memo)}"')
    if txn.extra:
        extra_json = json.dumps(txn.extra, sort_keys=True)
        lines.append(f'  simplefin-extra: "{_escape(extra_json)}"')
    lines.append(f"  {txn.asset_account}   {txn.amount} {txn.currency}")
    lines.append("  Expenses:Unknown")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_balance_line(bal: NormalizedBalance) -> str:
    return f"{bal.assertion_date.isoformat()} balance {bal.account}   {bal.amount} {bal.currency}"


def render_balances_file(balances: list[NormalizedBalance]) -> str:
    """Whole-file content for `balances.beancount`.

    Wholesale, not merged: `sync.py` calls this with the *current* sync's
    balances only, every time, so an account that stops being reported by
    SimpleFIN (closed, connection revoked) simply stops having a line here
    -- rather than a stale assertion surviving forever from a prior sync
    and permanently failing bean-check against data that no longer exists.
    """
    ordered = sorted(balances, key=lambda bal: bal.account)
    body = "\n".join(render_balance_line(bal) for bal in ordered)
    if body:
        body += "\n"
    return _BALANCES_HEADER + body


def render_opening_balance(ob: OpeningBalance) -> str:
    """Render a one-time `Equity:Opening-Balances` plug (see `OpeningBalance`).

    Deliberately does *not* share `simplefin-id`/`simplefin-account` dedup
    metadata with `render_transaction`'s output: this isn't a fetched
    transaction, and conflating the two dedup mechanisms risked either a
    real transaction id colliding with the marker or an opening entry
    being silently skipped as "just another transaction we've seen."
    `simplefin-opening: "true"` paired with `simplefin-account` is its own,
    separately-scanned marker (`ingest/dedup.py`).
    """
    return (
        f'{ob.entry_date.isoformat()} * "Opening balance (SimpleFIN backfill)"\n'
        f'  simplefin-account: "{ob.asset_account}"\n'
        f'  simplefin-opening: "true"\n'
        f"  {ob.asset_account}   {ob.amount} {ob.currency}\n"
        f"  Equity:Opening-Balances\n"
        f"\n"
    )


def render_accounts_simplefin_file(opens: list[AssetAccountOpen], open_date) -> str:
    """Whole-file content for `accounts-simplefin.beancount`.

    `opens` must already be in the order desired in the file --
    `normalize.discover_asset_accounts` sorts by name for determinism.
    """
    body = "\n".join(f"{open_date.isoformat()} open {o.asset_account}   {o.currency}" for o in opens)
    if body:
        body += "\n"
    return _ACCOUNTS_SIMPLEFIN_HEADER + body
